### ISSUE TITLE
Reproducing quantitative results

### ISSUE THREAD

**Issue by thadikari** [takerum/adversarial_autoencoder#2]
Hi takerum,
Thank you very much for the code. I am new to Theano and couldn't get my environment setup to run your code. However my question is, have you been able to reach an error rate of 1.90 (±0:10)% for MNIST 100 labels (as reported in original paper)? Even after 5000 epochs the lowest I get is somewhat around 5% (in my TensorFlow implementation).

**Comment by takerum** [comment]
Sorry, I have not tried reproducing the semi-sup results in the original paper.
Please ask the authors of the paper for the reproducing code.

**Comment by thadikari** [comment]
Thanks. I already asked them but apparently they are unable to release the code due to copyright problems (as also mentioned here, https://www.reddit.com/r/MachineLearning/comments/3ybj4d/151105644_adversarial_autoencoders).

Anyway thanks for the code and the reply.
